// [530-PROVENANCE]
/* **************************************************************************
 * PROJECT: 5:30 Protocol | COMPLIANCE: 2026.AI-ACT.ARTICLE-50
 * PROVENANCE: AI-GENERATED
 * AGENT_ID: GitHub-Copilot-Claude-Sonnet-4.6 | AUTHOR_ID: Five30-Protocol-Team
 * SECURITY_STATUS: STEEL-CHECK-PASSED
 * ************************************************************************** */

using System;

namespace Project530.Core.Common.Models;

/// <summary>
/// Blueprint proposal generated by gap analysis and generative systems.
/// Represents a system-suggested mod or improvement.
/// </summary>
public sealed record Object_GenerativeProposal
{
    public int Id { get; init; }
    public string Title { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public double ConfidenceScore { get; init; } = 0.0;
    public string SuggestedAgentId { get; init; } = string.Empty;
    public string Status { get; init; } = "Pending";
    public DateTime CreatedUtc { get; init; } = DateTime.UtcNow;
    public string Metadata { get; init; } = string.Empty;
}
